spring:
  datasource:
    url: jdbc:postgresql://data-storage:5432/access_control_db
    username: admin
    password: admin123
    hikari:
      initialization-fail-timeout: 60000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080