spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/access_control_db
    username: admin
    password: admin123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080